[project]
name = "simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent-torch>=0.6.0",
    "epiweeks>=2.3.0",
    "mcp[cli]>=1.6.0",
    "scipy>=1.15.2",
]
